local_costmap:
   global_frame: laser_odom
   robot_base_frame: base_footprint
   update_frequency: 3.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.01
   transform_tolerance: 1.0
   map_type: costmap
   # plugins:
   #    - {name: 3DPerception, type: 'costmap_depth_camera::DepthCameraObstacleLayer'}
   #    - {name: inflation, type: 'costmap_2d::InflationLayer'}
   # inflation:
   #    inflation_radius: 1.0
   #    cost_scaling_factor: 0.5
   # 3DPerception:
   #    ec_seg_distance: 0.2
   #    ec_cluster_min_size: 5
   #    size_of_cluster_rejection: 5
   #    voxel_resolution: 0.01
   #    check_radius: 0.1
   #    enable_near_blocked_protection: false
   #    number_points_considered_as_blocked: 5
   #    forced_clearing_distance: 0.1
   #    observation_sources: depth_cam #depth_cam_left
   #    depth_cam: {sensor_frame: camera_link, topic: /camera/depth/points, expected_update_rate: 0.3, FOV_W: 1.0, FOV_V: 0.9, min_detect_distance: 0.15, max_detect_distance: 2.0, min_obstacle_height: 0.08}
      #depth_cam_left: {sensor_frame: camera_link_left, topic: /camera_left/depth/color/points, expected_update_rate: 0.3, FOV_W: 1.0, FOV_V: 0.9, min_detect_distance: 0.15, max_detect_distance: 2.0, min_obstacle_height: 0.08}

  
   